apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
