apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dGVzdF9yb290
  MYSQL_DATABASE: c3lmZQ==
  MYSQL_USER: dGVzdA==
  MYSQL_PASSWORD: dGVzdA==
